# -*- coding: utf-8 -*-
"""DAY4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xdz8WlBcxz3VwxpgnkOXePOx1bDg2o1O
"""

import re

def get_population(city : str) -> str:
  city_lower=city.lower()
  if "tokyo" in city_lower:
    return "Observation :  The population of Tokyo is approximately 14.0 million."
  else:
    return f"Observation : Population not available for {city}."


def get_weather(location: str) -> str:
  location_lower=location.lower()
  if "london" in location_lower:
    return "Observation : Current weather in London : 12 degrees C."
  else:
    return f"Observation : Weather not available for {location}."

known_actions = {
    "get_population": get_population,
    "get_weather": get_weather
}

REACT_PROMPT="""
You are an AI assistant that can use tools to answer questions.
You have the following tools available:
get_population(city: str) -> str: Retrieves the approximate current population of a given city.
get_weather(location: str) -> str: Retrieves the current weather conditions for a given location.

To use a tool, use the following format:
Thought: You should always think about what to do.
Action: tool_name
Action Input: tool_input

To give a final answer, use the following format:
Thought: I have gathered enough information.
Final Answer: The final answer to the original question.

Begin!

Question: {question}
"""

question = "What is the population of Tokyo and the current weather in London?"
llm_response="""Thought: I need to find the population of Tokyo and the weather in London. I will start by getting the population of Tokyo.
Action: get_population
Action Input: Tokyo"""
print(llm_response)

action_1=re.search(r"Action :(\w+)",llm_response)
action_2=re.search(r"Action :(.*)",llm_response)

get_population("india")