# -*- coding: utf-8 -*-
"""sample_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZdY66NqEpaUBFKaRrn5ATwxUz6kI3HC
"""

import time

LIGHT_RED="RED"
LIGHT_YELLOW="YELLOW"
LIGHT_GREEN="GREEN"

DURATION_RED=15
DURATION_YELLOW=5
DURATION_GREEN=20

current_light_state=LIGHT_RED
time_in_current_state=0


def run_traffic_agent():
  global current_light_state,time_in_current_state
  print("Traffic Light AGent is Started")
  while True:
    time_in_current_state+=1
    if current_light_state==LIGHT_RED and time_in_current_state>=DURATION_RED:
      current_light_state=LIGHT_GREEN
      time_in_current_state=0
      print(f"\n----Chaning state : {LIGHT_GREEN}\n")
    elif current_light_state==LIGHT_GREEN and time_in_current_state>=DURATION_GREEN:
      current_light_state=LIGHT_YELLOW
      time_in_current_state=0
      print(f"\n----Chaning state : {LIGHT_YELLOW}\n")
    elif current_light_state==LIGHT_YELLOW and time_in_current_state>=DURATION_YELLOW:
      current_light_state=LIGHT_RED
      time_in_current_state=0
      print(f"\n----Chaning state : {LIGHT_RED}\n")

    print(f"Current State : {current_light_state}")
    print(f"Time in Current State : {time_in_current_state}")


    time.sleep(1)





if __name__=="__main__":
  try:
    run_traffic_agent()
  except KeyboardInterrupt:
    print("Traffic Light Agent Stopped")
  except Exception as e:
    print(f"An error occured : {e}")